import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[font]
size = 9.0

[font.bold]
family = "gohufont11nerdfontmono"
style = "Bold"

[font.bold_italic]
family = "gohufont11nerdfontmono"
style = "Bold Italic"

[font.italic]
family = "gohufont11nerdfontmono"
style = "Italic"

[font.normal]
family = "gohufont11nerdfontmono"
style = "Regular"

