#!/usr/bin/env bash

# You can call this script like this:
# $ ./volumeControl.sh up
# $ ./volumeControl.sh down
# $ ./volumeControl.sh mute

# Script modified from these wonderful people:
# https://github.com/dastorm/volume-notification-dunst/blob/master/volume.sh
# https://gist.github.com/sebastiencs/5d7227f388d93374cebdf72e783fbd6a

function get_volume {
  pactl get-sink-volume 0 | grep '%' | cut -d '/' -f 2 | cut -d '%' -f 1
}

function is_mute {
  pactl get-sink-mute 0 | cut -d ':' -f 2
  # amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function toggle_mute {
	check=$(is_mute)
	echo $check
	if [ "$check" = " yes" ]; then
		dunstify -a "Volume" muted
	else
		dunstify -a "Volume" unmuted
	fi
}
		


function send_notification {
    volume=$(get_volume)
    bar=$(seq --separator="─" 0 "$((volume / 5))" | sed 's/[0-9]//g')
    dunstify -a "Volume" -r 2593 -u normal "$bar"
}

case $1 in
  up)
	pactl set-sink-volume 0 +5%
    send_notification
    ;;
  down)
	pactl set-sink-volume 0 -5%
    send_notification
    ;;
  mute)
    # toggle mute
	pactl set-sink-mute 0 toggle
	toggle_mute
    ;;
esac
